### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by abolinhas** [austinlyons/dcjs-leaflet-untappd#4]
Hi,
The link of the demo https://austinlyons.github.io/dcjs-leaflet-untappd in not working, returns the error ERR_NAME_NOT_RESOLVED

**Comment by austinlyons** [comment]
Thanks. Looks like something I'll need to fix on my end. In the meantime, you can download the repo and run it locally yourself to try it out.

[See this section on one way to do that](https://github.com/austinlyons/dcjs-leaflet-untappd#try-it-yourself)
